source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

flutter_application_path = '../vp_flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')


def all_pods
    pod 'Masonry', '~> 1.1.0'
    pod 'WHDebugTool', '~>2.1'
    pod 'Masonry', '~> 1.1.0'

end

target 'hupuios' do
  
  install_all_flutter_pods(flutter_application_path)

  use_frameworks!
  inhibit_all_warnings!
  all_pods

end

